package lexer.daos;

/**
 * This file is automatically generated
 * Do not manually update! (Use the CompilerTools to regenerate.)
 **/
public enum TokenKind {
    // Special TokenKind for internal use
    BogusToken,

    // Generated TokenKinds
    Program, IntType, BooleanType, If, Then,
    Else, While, Function, Return, Identifier,
    IntLit, LeftBrace, RightBrace, LeftParen, RightParen,
    Comma, Assign, Equal, NotEqual, Less,
    LessEqual, Plus, Minus, Or, And,
    Multiply, Divide, Comment, Greater, GreaterEqual,
    Number, NumberLit, CharType, CharLit, From,
    To, Step,

    // Special TokenKind for internal use
    EOF
}
